kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:20
    commands:
      - npm install
      - npm run build
      - mkdir -p deploy
      - cp -rv dist deploy/
      - cp server.mjs deploy/
      - cp package.json deploy/
      - cp package-lock.json deploy/
      - cd deploy && npm install --omit=dev

  - name: Deploy
    image: docker:27-cli
    commands:
      - docker ps
      - docker volume create ff_website
      - docker run --rm -v ff_website:/target alpine sh -c "rm -rf /target/*"
      - tar -C deploy -cf - . | docker run --rm -i -v ff_website:/target alpine sh -c "tar -C /target -xf -"
      - docker stop ff_website || true
      - docker rm ff_website || true
      - |
        docker run -d \
          --name ff_website \
          --restart always \
          -p 680:3001 \
          -p 6443:3001 \
          -v ff_website:/app \
          -w /app \
          node:20-alpine node server.mjs
