kind: pipeline
type: docker
name: default

steps:
  - name: Build
    image: node:20
    commands:
      - npm install
      - npm run build
      - mkdir deploy
      - cp -rv dist deploy/
      - cp server.mjs deploy/
      - cp package.json deploy/
      - cp package-lock.json deploy/
      - cd deploy && npm install --omit=dev

  - name: Upload
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: address
      username: root
      password:
        from_secret: ssh_password
      source: deploy/
      target: /var/lib/docker/volumes/ff_website/_data
      strip_components: 1

  - name: Deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: address
      username: root
      password:
        from_secret: ssh_password
      script:
        - docker stop ff_website || true
        - docker rm ff_website || true
        - |
          docker run -d \
            --name ff_website \
            --restart always \
            -p 680:3001 \
            -p 6443:3001 \
            -v ff_website:/app \
            -w /app \
            node:20-alpine node server.mjs
